source 'https://rubygems.org'
ruby '2.1.4'

gem 'sqlite3'
gem 'activerecord'
gem "interactor", "~> 3.0"
gem 'ice_cube'
gem 'rspec'
gem "database_cleaner"
gem 'factory_girl'
gem 'faker'
gem 'shoulda-matchers'